module.exports = {
  'gallery': function (browser) {
    browser
    .url('http://localhost:8080/examples/gallery/')
      .waitForElementVisible('#app', 1000)
      .assert.elementNotPresent('.modal-slideshow')
      .click('img:nth-child(1)')
      .waitFor(500)
      .assert.elementPresent('.modal-slideshow')
      .assert.cssClassPresent('.modal-slideshow__gallery__container__img:nth-child(1)', 'modal-slideshow__gallery__container__img--active')
      .assert.cssClassNotPresent('.modal-slideshow__gallery__container__img:nth-child(2)', 'modal-slideshow__gallery__container__img--active')
      .assert.containsText('.modal-slideshow__gallery__title', '1 / 10')
      .click('.modal-slideshow__next')
      .waitFor(500)
      .assert.cssClassPresent('.modal-slideshow__gallery__container__img:nth-child(2)', 'modal-slideshow__gallery__container__img--active')
      .assert.containsText('.modal-slideshow__gallery__title', '2 / 10')
      .click('.modal-slideshow__container__image__img')
      .waitFor(500)
      .assert.cssClassPresent('.modal-slideshow__gallery__container__img:nth-child(3)', 'modal-slideshow__gallery__container__img--active')
      .assert.containsText('.modal-slideshow__gallery__title', '3 / 10')
      .click('.modal-slideshow__prev')
      .waitFor(500)
      .assert.cssClassPresent('.modal-slideshow__gallery__container__img:nth-child(2)', 'modal-slideshow__gallery__container__img--active')
      .assert.containsText('.modal-slideshow__gallery__title', '2 / 10')
      .click('.modal-slideshow__gallery__container__img:nth-child(4)')
      .waitFor(500)
      .assert.cssClassPresent('.modal-slideshow__gallery__container__img:nth-child(4)', 'modal-slideshow__gallery__container__img--active')
      .assert.containsText('.modal-slideshow__gallery__title', '4 / 10')
      .click('.modal-slideshow__close')
      .waitFor(500)
      .assert.elementNotPresent('.modal-slideshow')
      .end()
  }
}
